### ISSUE TITLE
Not branch aware

### ISSUE THREAD

**Issue by iamsubingyawali** [jelastic-jps/git-push-deploy#15]
I set up this add-on to take updates from my `main` branch but it takes updates from my `development` branch too.

The ROOT context updates as soon as I push updates to my `development` branch and again updates if I merge my branches.

**Comment by iamsubingyawali** [comment]
I tested again and found out that it was just updating the ROOT context but not actually fetching updates from other branches.

**Comment by Habibouldmoussa** [comment]
hello I have exactly the same problem I reopen this issue because for me it is not clear and it is not normal that we update a branch and that it is another branch which is updated and It disorients me, I don’t understand

Sincerely
